### ISSUE TITLE
set default (selected) for selectizeInput

### ISSUE THREAD

**Issue by kdaily** [davesteps/shinyFilters#1]
I'm trying to set the default value selected for each of my `filterInput`s. The docs suggest that I can pass on parameters for `selectizeInput` through `...` but using `selected='myvalue'` doesn't seem to work.

This is for `shinyFilters==0.1.0`.

**Comment by kdaily** [comment]
Oops - I read the `selectizeInput` docs wrong. Apparently there isn't a `selected` option, only for `selectInput`. Do you have knowledge of how to get a default selected?

**Comment by BetweenTwoTests** [comment]
@kdaily 
```
filterInput(f1,
    # Selectize options
    selected=NULL,
    options = list(placeholder = "My PlaceHolders", maxItems = 1)
```

**Comment by davesteps** [comment]
Hi, things have changed quite alot recently. But you can still use filterInput to set up your filters. Arguments are passed through to the ui elements. So the following should work. 
```
filterSet <- newFilterSet('FS1') %>%
  addSelectFilter('cyl')

# in UI
filterInput(filterSet, 'cyl',label='Cylinders',selected=c('3'))`

```
