### ISSUE TITLE
Add a label for the filter

### ISSUE THREAD

**Issue by SShamiri** [davesteps/shinyFilters#2]
is it possible to add a label to the filter to be displayed in the UI instead of using id as label?

**Comment by davesteps** [comment]
Hi, You can create the filterUIs indivudally using `filterInput`. The arguments are then passed through to the UI.  So the code from would be something like:

```
filterSet <- newFilterSet('FS1') %>%
  addSelectFilter('cyl')

# in UI
filterInput(filterSet, 'cyl',label='Cylinders')`
```

**Comment by SShamiri** [comment]
Thanks!
